spring:
  #rabbitmq相关配置 15672是Web管理界面的端口；5672是MQ访问的端口
 rabbitmq:
    host: 123.57.145.76
    port: 5672
    username: admin
    password: admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://123.57.145.76:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
congif:
  info: this is config info 3.0
